"""Email report delivery service."""

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email import encoders
import io

from app.core.config import settings


def send_report_email(
    to_email: str,
    filename: str,
    pdf_buffer: io.BytesIO,
) -> bool:
    """Send a PDF report via email. Returns True on success."""
    if not settings.SMTP_USER or not settings.SMTP_PASSWORD:
        raise ValueError("SMTP credentials not configured. Set SMTP_USER and SMTP_PASSWORD in .env")

    msg = MIMEMultipart()
    msg["From"] = settings.SMTP_FROM or settings.SMTP_USER
    msg["To"] = to_email
    msg["Subject"] = f"AI Analysis Report - {filename}"

    body = f"""Hello,

Please find attached the AI-generated analysis report for "{filename}".

This report includes:
- Document summary and key insights
- Trend analysis and recommendations
- Visual charts and data statistics

Generated by AI Data Analysis Platform.
"""
    msg.attach(MIMEText(body, "plain"))

    attachment = MIMEBase("application", "pdf")
    pdf_buffer.seek(0)
    attachment.set_payload(pdf_buffer.read())
    encoders.encode_base64(attachment)
    attachment.add_header(
        "Content-Disposition",
        f'attachment; filename="analysis_report_{filename}.pdf"',
    )
    msg.attach(attachment)

    with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT) as server:
        server.starttls()
        server.login(settings.SMTP_USER, settings.SMTP_PASSWORD)
        server.send_message(msg)

    return True
