import io
import math
import os
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN

from app.models.schemas import AnalysisResponse, DashboardResponse
from app.services.report import _generate_chart_image

def generate_pptx_report(
    filename: str,
    analysis: AnalysisResponse,
    dashboard: DashboardResponse | None = None,
) -> io.BytesIO:
    prs = Presentation()
    
    # Slide 1: Title
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    
    title.text = "Executive Business Case"
    subtitle.text = f"Source file: {filename}\nGenerated by AI Data Analysis Platform"

    # Profile Badge
    if dashboard and dashboard.detection_profile:
        subtitle.text += f"\nDataset Intelligence: {dashboard.detection_profile}"

    # Slide 2: Executive Summary
    summary_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(summary_layout)
    title, body = slide.shapes.title, slide.placeholders[1]
    title.text = "Executive Summary"
    tf = body.text_frame
    tf.text = analysis.summary

    # Slide 3: Financial Performance 
    if dashboard and dashboard.profit_loss:
        slide = prs.slides.add_slide(prs.slide_layouts[5])
        slide.shapes.title.text = "Financial Performance"
        
        pl = dashboard.profit_loss
        rows, cols = 5, 2
        left, top, width, height = Inches(1), Inches(2), Inches(8), Inches(2)
        table = slide.shapes.add_table(rows, cols, left, top, width, height).table
        
        table.cell(0, 0).text = "Metric"
        table.cell(0, 1).text = "Value"
        table.cell(1, 0).text = "Total Revenue"
        table.cell(1, 1).text = f"${pl.total_revenue:,.2f}" if not math.isnan(pl.total_revenue) else "$0.00"
        table.cell(2, 0).text = "Total Cost"
        table.cell(2, 1).text = f"${pl.total_cost:,.2f}" if not math.isnan(pl.total_cost) else "$0.00"
        table.cell(3, 0).text = "Net Profit"
        profit_val = pl.total_profit if hasattr(pl, "total_profit") and not math.isnan(getattr(pl, "total_profit", float('nan'))) else pl.net_profit if not math.isnan(pl.net_profit) else 0.0
        table.cell(3, 1).text = f"${profit_val:,.2f}"
        table.cell(4, 0).text = "Margin"
        table.cell(4, 1).text = f"{pl.margin_percentage}%" if not math.isnan(pl.margin_percentage) else "0%"

    # Slide 4: Key Insights & Trends
    slide = prs.slides.add_slide(summary_layout)
    title, body = slide.shapes.title, slide.placeholders[1]
    title.text = "Key Insights & Trends"
    tf = body.text_frame
    
    if analysis.key_insights:
        p = tf.add_paragraph()
        p.text = "Insights:"
        p.font.bold = True
        for insight in analysis.key_insights[:3]:  # Max 3 for space
            p = tf.add_paragraph()
            p.text = str(insight)
            p.level = 1

    if analysis.trends:
        p = tf.add_paragraph()
        p.text = "Trends:"
        p.font.bold = True
        for trend in analysis.trends[:3]: # Max 3 for space
            p = tf.add_paragraph()
            p.text = str(trend)
            p.level = 1

    # Slide 5: Recommendations
    slide = prs.slides.add_slide(summary_layout)
    title, body = slide.shapes.title, slide.placeholders[1]
    title.text = "Strategic Recommendations"
    tf = body.text_frame
    
    if dashboard and dashboard.growth_suggestions:
        for suggestion in dashboard.growth_suggestions[:4]:
            p = tf.add_paragraph()
            p.text = f"{suggestion.title} (Impact: {suggestion.impact})"
            p.font.bold = True
            p = tf.add_paragraph()
            p.text = str(suggestion.description)
            p.level = 1
    elif analysis.recommendations:
        for rec in analysis.recommendations[:4]:
            p = tf.add_paragraph()
            p.text = str(rec)

    # Slide 6+: Charts
    if dashboard and dashboard.charts:
        for chart in dashboard.charts:
            chart_dict = chart.model_dump() if hasattr(chart, "model_dump") else chart.__dict__
            img_buf = _generate_chart_image(chart_dict)
            if img_buf:
                slide = prs.slides.add_slide(prs.slide_layouts[5])
                slide.shapes.title.text = str(chart_dict.get("title", "Visual Analysis"))
                
                # Add image
                left, top = Inches(1), Inches(1.5)
                pic = slide.shapes.add_picture(img_buf, left, top, width=Inches(8))
                
                # Add description
                desc_left, desc_top = Inches(1), top + pic.height + Inches(0.2)
                txBox = slide.shapes.add_textbox(desc_left, desc_top, Inches(8), Inches(1))
                tf = txBox.text_frame
                tf.word_wrap = True
                p = tf.paragraphs[0]
                p.text = str(chart_dict.get("description", ""))
                p.font.size = Pt(12)

    # Save to BytesIO
    buffer = io.BytesIO()
    prs.save(buffer)
    buffer.seek(0)
    return buffer
