"use client";

import { useState, useEffect, Suspense } from "react";
import { useSearchParams } from "next/navigation";
import { Loader2, FileText, AlertCircle } from "lucide-react";
import { getSharedReport, type SharedReportResponse } from "@/lib/api";

function SharedReportContent() {
  const searchParams = useSearchParams();
  const shareId = searchParams.get("id");
  const [report, setReport] = useState<SharedReportResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!shareId) {
      setError("No share ID provided");
      setLoading(false);
      return;
    }
    getSharedReport(shareId)
      .then(setReport)
      .catch((err) => setError(err.response?.data?.detail || "Failed to load shared report"))
      .finally(() => setLoading(false));
  }, [shareId]);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <Loader2 className="w-8 h-8 text-primary-500 animate-spin mx-auto mb-4" />
          <p className="text-slate-400">Loading shared report...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center glass-card p-8 max-w-md">
          <AlertCircle className="w-10 h-10 text-red-400 mx-auto mb-3" />
          <p className="text-red-400">{error}</p>
        </div>
      </div>
    );
  }

  if (!report) return null;

  return (
    <div className="min-h-screen py-8 px-4">
      <div className="max-w-4xl mx-auto space-y-6">
        <div className="glass-card p-6 text-center">
          <FileText className="w-10 h-10 text-primary-400 mx-auto mb-3" />
          <h1 className="text-xl font-bold">Shared Analysis Report</h1>
          <p className="text-sm text-slate-400 mt-1">{report.filename}</p>
          <p className="text-xs text-slate-600 mt-1">
            Created {new Date(report.created_at).toLocaleDateString()}
          </p>
        </div>

        {report.analysis && (
          <div className="space-y-4">
            <div className="glass-card p-6">
              <h2 className="text-lg font-semibold mb-3">Summary</h2>
              <p className="text-slate-300 text-sm leading-relaxed">{report.analysis.summary}</p>
            </div>
            <div className="grid md:grid-cols-2 gap-4">
              <div className="glass-card p-6">
                <h3 className="font-semibold mb-2 text-yellow-400">Key Insights</h3>
                <ul className="space-y-1">
                  {report.analysis.key_insights.map((ins, i) => (
                    <li key={i} className="text-sm text-slate-300">- {ins}</li>
                  ))}
                </ul>
              </div>
              <div className="glass-card p-6">
                <h3 className="font-semibold mb-2 text-green-400">Trends</h3>
                <ul className="space-y-1">
                  {report.analysis.trends.map((t, i) => (
                    <li key={i} className="text-sm text-slate-300">- {t}</li>
                  ))}
                </ul>
              </div>
            </div>
            <div className="glass-card p-6">
              <h3 className="font-semibold mb-2 text-purple-400">Recommendations</h3>
              <ul className="space-y-1">
                {report.analysis.recommendations.map((r, i) => (
                  <li key={i} className="text-sm text-slate-300">{i + 1}. {r}</li>
                ))}
              </ul>
            </div>
          </div>
        )}

        {report.dashboard && report.dashboard.charts.length > 0 && (
          <div className="glass-card p-6">
            <h2 className="text-lg font-semibold mb-4">Visual Dashboard</h2>
            <p className="text-sm text-slate-500">
              {report.dashboard.charts.length} charts generated. View the full interactive dashboard by uploading the file directly.
            </p>
            <div className="mt-4 grid md:grid-cols-2 gap-4">
              {report.dashboard.charts.map((chart, i) => (
                <div key={i} className="bg-slate-800/50 rounded-lg p-4">
                  <h4 className="font-medium text-sm">{chart.title}</h4>
                  <p className="text-xs text-slate-500 mt-1">{chart.description}</p>
                  <p className="text-xs text-slate-600 mt-2">Type: {chart.chart_type}</p>
                </div>
              ))}
            </div>
          </div>
        )}

        <div className="text-center text-xs text-slate-600 py-4">
          Generated by AI Data Analysis Platform
        </div>
      </div>
    </div>
  );
}

export default function SharedReportPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen flex items-center justify-center">
        <Loader2 className="w-8 h-8 text-primary-500 animate-spin" />
      </div>
    }>
      <SharedReportContent />
    </Suspense>
  );
}
